name: Run K6 Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  k6-tests:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Instalar o K6
      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y k6

      # Step 3: Compilar os arquivos TypeScript
      - name: Compile TypeScript
        run: npx tsc --project k6/tsconfig.json

      # Step 4: Rodar os testes no K6
      - name: Run K6 tests
        run: |
          k6 run k6/tests/load-tests/loadTestHome.ts