name: Run K6 Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  k6-tests:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Instalar o K6
      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      # Step 3: Compilar os arquivos TypeScript
      - name: Compile TypeScript
        run: npx tsc --project tsconfig.json

      # Step 4: Rodar os testes no K6
      - name: Run K6 tests
        run: |
          k6 run k6/tests/load-tests/loadTestHome.ts